variable "auth_token" {}
variable "project_id" {}
variable "public_ips_net" {}
variable "edge_hostname" {}
variable "edge_size" {}
variable "metro" {}
variable "edge_os" {}
variable "billing_cycle" {}
variable "pub_ip" {}
variable "ipblock_desc" {}
